### ISSUE TITLE
localization of simp chinese

### ISSUE THREAD

**Issue by xiaolingtong** [Stoklomolvi/better-recognition-mod#1]
你好，我已经该模组的中文的本地化问附上，你能适当的时候将其加入模组吗？感谢
Hello, I have attached the Chinese localization of this module, can you add it to the module at an appropriate time? Thank you！
![20240804125434_1 - 副本](https://github.com/user-attachments/assets/eee46f94-c070-4ebd-93f9-59f80dd3ea92)
[simp_chinese 2.zip](https://github.com/user-attachments/files/16486404/simp_chinese.2.zip)

**Comment by Stoklomolvi** [comment]
Merged 7eed335cf10ad2d91a83279171cb72d0e7454ec7; done, thanks for the addition! 多谢提供简体中文翻译！
